# Generated by Django 6.1.1 on 2026-09-03 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=120)),
                ('last_name', models.CharField(db_index=True, max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('mobile', models.CharField(blank=True, default='', max_length=32)),
                ('job_title', models.CharField(blank=True, default='', max_length=120)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('company_name', models.CharField(blank=True, default='', help_text='Associated company or organization name', max_length=180)),
                ('lifecycle_stage', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('opportunity', 'Opportunity'), ('customer', 'Customer'), ('churned', 'Churned'), ('partner', 'Partner')], db_index=True, default='lead', max_length=32)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Assigned CRM user responsible for this contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='contacts_co_last_na_bb56ce_idx'), models.Index(fields=['lifecycle_stage', 'created_at'], name='contacts_co_lifecyc_40c7b8_idx')],
            },
        ),
    ]
