# Generated by Django 6.1.1 on 2026-09-03 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=120)),
                ('last_name', models.CharField(db_index=True, max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('company_name', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('job_title', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('converted', 'Converted')], db_index=True, default='new', max_length=32)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('cold_outreach', 'Cold Outreach'), ('event', 'Event / Conference'), ('advertisement', 'Advertisement'), ('partner', 'Partner'), ('other', 'Other')], db_index=True, default='website', max_length=50)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Potential pipeline or contract value if qualified', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Assigned sales representative or SDR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='leads_lead_last_na_e542ff_idx'), models.Index(fields=['status', 'created_at'], name='leads_lead_status_2b0e1e_idx'), models.Index(fields=['source', 'created_at'], name='leads_lead_source_ebb051_idx')],
            },
        ),
    ]
