# Generated by Django 6.1.1 on 2026-09-03 16:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('contacts', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total contractual or deal financial value', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('proposal', 'Proposal / Pitch'), ('negotiation', 'Negotiation / Review'), ('won', 'Closed Won'), ('lost', 'Closed Lost')], db_index=True, default='prospecting', max_length=32)),
                ('probability', models.PositiveIntegerField(default=10, help_text='Estimated win probability percentage (0 - 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('close_date', models.DateField(blank=True, db_index=True, help_text='Expected or actual closing date', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Associated business account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='companies.company')),
                ('contact', models.ForeignKey(blank=True, help_text='Primary customer contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='contacts.contact')),
                ('lead', models.ForeignKey(blank=True, help_text='Originating lead record if converted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.lead')),
                ('owner', models.ForeignKey(blank=True, help_text='Assigned account executive or sales representative', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stage', 'created_at'], name='deals_deal_stage_13d9f9_idx'), models.Index(fields=['close_date'], name='deals_deal_close_d_5c52f4_idx'), models.Index(fields=['value'], name='deals_deal_value_733033_idx')],
            },
        ),
    ]
